// next-mylendingsolution/src/components/atoms/LinkBtn.tsx
import Link from "next/link";

interface LinkBtnProps {
  href: string;
  children: React.ReactNode;
  variant?: "primary" | "secondary" | "outline" | "ghost";
  className?: string;
  onClick?: () => void;
}

const variants: Record<string, string> = {
  primary: "bg-primary text-white hover:bg-primary/90",
  secondary: "bg-secondary text-white hover:bg-secondary/90",
  outline: "border border-primary text-primary hover:bg-primary/10",
  ghost: "text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-white/5",
};

export default function LinkBtn({
  href, children, variant = "primary", className = "", onClick
}: LinkBtnProps) {
  return (
    <Link
      href={href}
      onClick={onClick}
      className={`inline-flex items-center justify-center px-6 py-3 rounded-xl font-semibold text-sm transition-all duration-300 ${variants[variant]} ${className}`}
    >
      {children}
    </Link>
  );
}

// components/atoms/LinkBtn.vue
<script lang="ts" setup>
const { href, variant, costumSpanClass="", costumTextColor="" } = defineProps<{
    href:string,
    variant:"primary"|"primary-outlined"|"secondary"|"secondary-outlined"|"costum",
    costumSpanClass?:string,
    costumTextColor?:string
}>()

let spanClass:string = "";
let textCl:string = ""
if (variant === "primary") {
    spanClass = "bg-primary border-2 border-transparent"
    textCl = "text-white"
}else if(variant === "primary-outlined"){
    spanClass = "border-2 border-primary"
    textCl = "text-primary"
}
else if(variant === "secondary"){
    spanClass = "bg-primary/5"
    textCl = "text-primary"
}
else if(variant === "costum"){
    spanClass=costumSpanClass
    textCl = costumTextColor
}else {
    spanClass=costumSpanClass
    textCl = costumTextColor
}

</script>
<template>
    <NuxtLink :to="href" class="px-6 md:px-7 py-3 rounded-full relative group">
        <span v-if="variant!=='costum'" class="absolute inset-0 rounded-full group-hover:scale-105 origin-center transition-all ease-in-out" :class="spanClass"></span>
        <span class="relative flex items-center justify-center" :class="textCl">
            <slot/>
        </span>
    </NuxtLink>
</template>
